/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{archive_apis::ResponseContent, archive_models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`subaccount_archive_controller_get_total_volume`]
#[derive(Clone, Debug, Default)]
pub struct SubaccountArchiveControllerGetTotalVolumeParams {
    /// Id of the subaccount to query for
    pub subaccount_id: String,
}

/// struct for passing parameters to the method [`subaccount_archive_controller_list_balance_history`]
#[derive(Clone, Debug, Default)]
pub struct SubaccountArchiveControllerListBalanceHistoryParams {
    /// Start time of the query range (clamped to resolution, ms since Unix epoch)
    pub start_time: f64,
    /// Resolution of the data to be returned
    pub resolution: String,
    /// Id of the subaccount to query for
    pub subaccount_id: String,
    /// Direction to paginate through objects
    pub order: Option<String>,
    /// Limit the number of objects to return
    pub limit: Option<i32>,
    /// Pointer to the current object in pagination dataset
    pub cursor: Option<String>,
    /// End time of the query range (clamped to resolution, ms since Unix epoch, defaults to now)
    pub end_time: Option<f64>,
    /// Order by field
    pub order_by: Option<String>,
}

/// struct for passing parameters to the method [`subaccount_archive_controller_list_position_funding_history`]
#[derive(Clone, Debug, Default)]
pub struct SubaccountArchiveControllerListPositionFundingHistoryParams {
    /// Start time of the query range (clamped to resolution, ms since Unix epoch)
    pub start_time: f64,
    /// Id of the subaccount to query for
    pub subaccount_id: String,
    /// Direction to paginate through objects
    pub order: Option<String>,
    /// Limit the number of objects to return
    pub limit: Option<i32>,
    /// Pointer to the current object in pagination dataset
    pub cursor: Option<String>,
    /// End time of the query range (clamped to resolution, ms since Unix epoch, defaults to now)
    pub end_time: Option<f64>,
    /// Order by field
    pub order_by: Option<String>,
    /// Array of position ids to filter for
    pub position_ids: Option<Vec<uuid::Uuid>>,
    /// Array of product ids to filter for
    pub product_ids: Option<Vec<uuid::Uuid>>,
}

/// struct for passing parameters to the method [`subaccount_archive_controller_list_unrealized_pnl_history`]
#[derive(Clone, Debug, Default)]
pub struct SubaccountArchiveControllerListUnrealizedPnlHistoryParams {
    /// Start time of the query range (clamped to resolution, ms since Unix epoch)
    pub start_time: f64,
    /// Resolution of the data to be returned (hourly or coarser only)
    pub resolution: String,
    /// Id of the subaccount to query for
    pub subaccount_id: String,
    /// Direction to paginate through objects
    pub order: Option<String>,
    /// Limit the number of objects to return
    pub limit: Option<i32>,
    /// Pointer to the current object in pagination dataset
    pub cursor: Option<String>,
    /// End time of the query range (clamped to resolution, ms since Unix epoch, defaults to now)
    pub end_time: Option<f64>,
    /// Order by field
    pub order_by: Option<String>,
    /// Array of product ids to filter for
    pub product_ids: Option<Vec<uuid::Uuid>>,
}

/// struct for passing parameters to the method [`subaccount_archive_controller_list_volume_history`]
#[derive(Clone, Debug, Default)]
pub struct SubaccountArchiveControllerListVolumeHistoryParams {
    /// Start time of the query range (clamped to resolution, ms since Unix epoch)
    pub start_time: f64,
    /// Resolution of the data to be returned
    pub resolution: String,
    /// Id of the subaccount to query for
    pub subaccount_id: String,
    /// Direction to paginate through objects
    pub order: Option<String>,
    /// Limit the number of objects to return
    pub limit: Option<i32>,
    /// Pointer to the current object in pagination dataset
    pub cursor: Option<String>,
    /// End time of the query range (clamped to resolution, ms since Unix epoch, defaults to now)
    pub end_time: Option<f64>,
    /// Order by field
    pub order_by: Option<String>,
}

/// struct for typed errors of method [`subaccount_archive_controller_get_total_volume`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubaccountArchiveControllerGetTotalVolumeError {
    Status400(archive_models::BadRequestDto),
    Status401(archive_models::UnauthorizedDto),
    Status403(archive_models::ForbiddenDto),
    Status404(archive_models::NotFoundDto),
    Status422(archive_models::UnprocessableEntityDto),
    Status429(archive_models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`subaccount_archive_controller_list_balance_history`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubaccountArchiveControllerListBalanceHistoryError {
    Status400(archive_models::BadRequestDto),
    Status401(archive_models::UnauthorizedDto),
    Status403(archive_models::ForbiddenDto),
    Status404(archive_models::NotFoundDto),
    Status422(archive_models::UnprocessableEntityDto),
    Status429(archive_models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`subaccount_archive_controller_list_position_funding_history`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubaccountArchiveControllerListPositionFundingHistoryError {
    Status400(archive_models::BadRequestDto),
    Status401(archive_models::UnauthorizedDto),
    Status403(archive_models::ForbiddenDto),
    Status404(archive_models::NotFoundDto),
    Status422(archive_models::UnprocessableEntityDto),
    Status429(archive_models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`subaccount_archive_controller_list_unrealized_pnl_history`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubaccountArchiveControllerListUnrealizedPnlHistoryError {
    Status400(archive_models::BadRequestDto),
    Status401(archive_models::UnauthorizedDto),
    Status403(archive_models::ForbiddenDto),
    Status404(archive_models::NotFoundDto),
    Status422(archive_models::UnprocessableEntityDto),
    Status429(archive_models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`subaccount_archive_controller_list_volume_history`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubaccountArchiveControllerListVolumeHistoryError {
    Status400(archive_models::BadRequestDto),
    Status401(archive_models::UnauthorizedDto),
    Status403(archive_models::ForbiddenDto),
    Status404(archive_models::NotFoundDto),
    Status422(archive_models::UnprocessableEntityDto),
    Status429(archive_models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

pub async fn subaccount_archive_controller_get_total_volume(
    configuration: &configuration::Configuration,
    params: SubaccountArchiveControllerGetTotalVolumeParams,
) -> Result<
    archive_models::TotalSubaccountVolumeDto,
    Error<SubaccountArchiveControllerGetTotalVolumeError>,
> {
    let uri_str = format!("{}/v1/subaccount/total-volume", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("subaccountId", &params.subaccount_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `archive_models::TotalSubaccountVolumeDto`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `archive_models::TotalSubaccountVolumeDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SubaccountArchiveControllerGetTotalVolumeError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn subaccount_archive_controller_list_balance_history(
    configuration: &configuration::Configuration,
    params: SubaccountArchiveControllerListBalanceHistoryParams,
) -> Result<
    archive_models::PageOfBalanceHistoryDtos,
    Error<SubaccountArchiveControllerListBalanceHistoryError>,
> {
    let uri_str = format!("{}/v1/subaccount/balance", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("startTime", &params.start_time.to_string())]);
    if let Some(ref param_value) = params.end_time {
        req_builder = req_builder.query(&[("endTime", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("resolution", &params.resolution.to_string())]);
    if let Some(ref param_value) = params.order_by {
        req_builder = req_builder.query(&[("orderBy", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("subaccountId", &params.subaccount_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `archive_models::PageOfBalanceHistoryDtos`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `archive_models::PageOfBalanceHistoryDtos`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SubaccountArchiveControllerListBalanceHistoryError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn subaccount_archive_controller_list_position_funding_history(
    configuration: &configuration::Configuration,
    params: SubaccountArchiveControllerListPositionFundingHistoryParams,
) -> Result<
    archive_models::PageOfPositionFundingHistoryDtos,
    Error<SubaccountArchiveControllerListPositionFundingHistoryError>,
> {
    let uri_str = format!("{}/v1/subaccount/funding", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("startTime", &params.start_time.to_string())]);
    if let Some(ref param_value) = params.end_time {
        req_builder = req_builder.query(&[("endTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.order_by {
        req_builder = req_builder.query(&[("orderBy", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("subaccountId", &params.subaccount_id.to_string())]);
    if let Some(ref param_value) = params.position_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .iter()
                    .map(|p| ("positionIds".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "positionIds",
                &param_value
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = params.product_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .iter()
                    .map(|p| ("productIds".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "productIds",
                &param_value
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `archive_models::PageOfPositionFundingHistoryDtos`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `archive_models::PageOfPositionFundingHistoryDtos`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SubaccountArchiveControllerListPositionFundingHistoryError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn subaccount_archive_controller_list_unrealized_pnl_history(
    configuration: &configuration::Configuration,
    params: SubaccountArchiveControllerListUnrealizedPnlHistoryParams,
) -> Result<
    archive_models::PageOfUnrealizedPnlHistoryDtos,
    Error<SubaccountArchiveControllerListUnrealizedPnlHistoryError>,
> {
    let uri_str = format!("{}/v1/subaccount/unrealized-pnl", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("startTime", &params.start_time.to_string())]);
    if let Some(ref param_value) = params.end_time {
        req_builder = req_builder.query(&[("endTime", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("resolution", &params.resolution.to_string())]);
    if let Some(ref param_value) = params.order_by {
        req_builder = req_builder.query(&[("orderBy", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("subaccountId", &params.subaccount_id.to_string())]);
    if let Some(ref param_value) = params.product_ids {
        req_builder = match "multi" {
            "multi" => req_builder.query(
                &param_value
                    .iter()
                    .map(|p| ("productIds".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "productIds",
                &param_value
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `archive_models::PageOfUnrealizedPnlHistoryDtos`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `archive_models::PageOfUnrealizedPnlHistoryDtos`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SubaccountArchiveControllerListUnrealizedPnlHistoryError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn subaccount_archive_controller_list_volume_history(
    configuration: &configuration::Configuration,
    params: SubaccountArchiveControllerListVolumeHistoryParams,
) -> Result<
    archive_models::PageOfSubaccountVolumeHistoryDtos,
    Error<SubaccountArchiveControllerListVolumeHistoryError>,
> {
    let uri_str = format!("{}/v1/subaccount/volume", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("startTime", &params.start_time.to_string())]);
    if let Some(ref param_value) = params.end_time {
        req_builder = req_builder.query(&[("endTime", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("resolution", &params.resolution.to_string())]);
    if let Some(ref param_value) = params.order_by {
        req_builder = req_builder.query(&[("orderBy", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("subaccountId", &params.subaccount_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `archive_models::PageOfSubaccountVolumeHistoryDtos`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `archive_models::PageOfSubaccountVolumeHistoryDtos`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SubaccountArchiveControllerListVolumeHistoryError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
