#![allow(clippy::empty_docs, clippy::too_many_arguments)]
/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceHistoryDto {
    /// Timestamp of the balance record (ms since Unix Epoch)
    #[serde(rename = "time")]
    pub time: f64,
    /// Cumulative trading fees paid up to this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "tradingFee")]
    pub trading_fee: String,
    /// Cumulative funding realized up to this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "realizedFunding")]
    pub realized_funding: String,
    /// Cumulative realized PnL up to this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "realizedPnl")]
    pub realized_pnl: String,
    /// Cumulative deposit fees paid up to this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "depositFee")]
    pub deposit_fee: String,
    /// Cumulative deposits made up to this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "deposit")]
    pub deposit: String,
    /// Cumulative withdrawal fees paid up to this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "withdrawalFee")]
    pub withdrawal_fee: String,
    /// Cumulative withdrawals made up to this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "withdrawal")]
    pub withdrawal: String,
    /// Total balance at this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "balance")]
    pub balance: String,
}

impl BalanceHistoryDto {
    pub fn new(
        time: f64,
        trading_fee: String,
        realized_funding: String,
        realized_pnl: String,
        deposit_fee: String,
        deposit: String,
        withdrawal_fee: String,
        withdrawal: String,
        balance: String,
    ) -> BalanceHistoryDto {
        BalanceHistoryDto {
            time,
            trading_fee,
            realized_funding,
            realized_pnl,
            deposit_fee,
            deposit,
            withdrawal_fee,
            withdrawal,
            balance,
        }
    }
}
