#![allow(clippy::empty_docs, clippy::too_many_arguments)]
/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::archive_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFoundDto {
    #[serde(rename = "statusCode")]
    pub status_code: StatusCode,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "error")]
    pub error: archive_models::NotFoundDtoErrorEnum,
}

impl NotFoundDto {
    pub fn new(
        status_code: StatusCode,
        message: String,
        error: archive_models::NotFoundDtoErrorEnum,
    ) -> NotFoundDto {
        NotFoundDto {
            status_code,
            message,
            error,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum StatusCode {
    #[serde(rename = "404")]
    #[default]
    Variant404,
}

