#![allow(clippy::empty_docs, clippy::too_many_arguments)]
/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */


use serde_repr::{Deserialize_repr, Serialize_repr};
/// OrderSide : Position side as either BUY (0) or SELL (1)
/// Position side as either BUY (0) or SELL (1)
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
#[derive(Default)]
pub enum OrderSide {
    #[default]
    BUY = 0,
    SELL = 1,
}

impl std::fmt::Display for OrderSide {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::BUY => "0",
                Self::SELL => "1",
            }
        )
    }
}
