#![allow(clippy::empty_docs, clippy::too_many_arguments)]
/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::archive_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PositionFundingHistoryDto {
    /// Timestamp of the funding charge (ms since Unix Epoch)
    #[serde(rename = "time")]
    pub time: f64,
    /// Timestamp of the funding settlement (ms since Unix Epoch)
    #[serde(rename = "settledAt")]
    pub settled_at: f64,
    /// Id representing the product
    #[serde(rename = "productId")]
    pub product_id: String,
    /// Product ticker
    #[serde(rename = "productTicker")]
    pub product_ticker: String,
    /// Id representing the position
    #[serde(rename = "positionId")]
    pub position_id: String,
    #[serde(rename = "positionSide")]
    pub position_side: archive_models::PositionSideEnum,
    /// Position quantity at the time of funding, expressed as a decimal (precision: 9)
    #[serde(rename = "positionQuantity")]
    pub position_quantity: String,
    /// Funding rate for the period, expressed as a decimal (precision: 9)
    #[serde(rename = "fundingRate")]
    pub funding_rate: String,
    /// Funding charge per unit in USD, expressed as a decimal (precision: 9)
    #[serde(rename = "chargePerUnitUsd")]
    pub charge_per_unit_usd: String,
    /// Total funding charge for the position (positive means pay, negative means receive), expressed as a decimal (precision: 9)
    #[serde(rename = "fundingCharge")]
    pub funding_charge: String,
}

impl PositionFundingHistoryDto {
    pub fn new(
        time: f64,
        settled_at: f64,
        product_id: String,
        product_ticker: String,
        position_id: String,
        position_side: archive_models::PositionSideEnum,
        position_quantity: String,
        funding_rate: String,
        charge_per_unit_usd: String,
        funding_charge: String,
    ) -> PositionFundingHistoryDto {
        PositionFundingHistoryDto {
            time,
            settled_at,
            product_id,
            product_ticker,
            position_id,
            position_side,
            position_quantity,
            funding_rate,
            charge_per_unit_usd,
            funding_charge,
        }
    }
}
