#![allow(clippy::empty_docs, clippy::too_many_arguments)]
/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductOpenInterestHistoryDto {
    /// Timestamp of the open interest record (ms since Unix Epoch)
    #[serde(rename = "time")]
    pub time: f64,
    /// Id representing the product
    #[serde(rename = "productId")]
    pub product_id: String,
    /// Open interest in USD at the end of this time interval, expressed as a decimal (precision: 9)
    #[serde(rename = "openInterest")]
    pub open_interest: String,
    /// Minimum open interest in USD during this time interval, expressed as a decimal (precision: 9)
    #[serde(rename = "openInterestMin")]
    pub open_interest_min: String,
    /// Maximum open interest in USD during this time interval, expressed as a decimal (precision: 9)
    #[serde(rename = "openInterestMax")]
    pub open_interest_max: String,
}

impl ProductOpenInterestHistoryDto {
    pub fn new(
        time: f64,
        product_id: String,
        open_interest: String,
        open_interest_min: String,
        open_interest_max: String,
    ) -> ProductOpenInterestHistoryDto {
        ProductOpenInterestHistoryDto {
            time,
            product_id,
            open_interest,
            open_interest_min,
            open_interest_max,
        }
    }
}
