#![allow(clippy::empty_docs, clippy::too_many_arguments)]
/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountVolumeHistoryDto {
    /// Timestamp of the volume record (ms since Unix Epoch)
    #[serde(rename = "time")]
    pub time: f64,
    /// Volume in USD during this time interval, expressed as a decimal (precision: 9)
    #[serde(rename = "volumeUsd")]
    pub volume_usd: rust_decimal::Decimal,
}

impl SubaccountVolumeHistoryDto {
    pub fn new(time: f64, volume_usd: rust_decimal::Decimal) -> SubaccountVolumeHistoryDto {
        SubaccountVolumeHistoryDto { time, volume_usd }
    }
}
