#![allow(clippy::empty_docs, clippy::too_many_arguments)]
/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// TooManyRequestsDtoErrorEnum : Extracted enum for TooManyRequestsDtoErrorEnum
/// Extracted enum for TooManyRequestsDtoErrorEnum
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum TooManyRequestsDtoErrorEnum {
    #[serde(rename = "Too Many Requests")]
    #[default]
    TooManyRequests,
}

impl std::fmt::Display for TooManyRequestsDtoErrorEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TooManyRequests => write!(f, "Too Many Requests"),
        }
    }
}

