#![allow(clippy::empty_docs, clippy::too_many_arguments)]
/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnrealizedPnlHistoryDto {
    /// Timestamp of the unrealized PnL record (ms since Unix Epoch)
    #[serde(rename = "time")]
    pub time: f64,
    /// Unrealized PnL at this point in time, expressed as a decimal (precision: 9)
    #[serde(rename = "unrealizedPnl")]
    pub unrealized_pnl: rust_decimal::Decimal,
}

impl UnrealizedPnlHistoryDto {
    pub fn new(time: f64, unrealized_pnl: rust_decimal::Decimal) -> UnrealizedPnlHistoryDto {
        UnrealizedPnlHistoryDto {
            time,
            unrealized_pnl,
        }
    }
}
