/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`referral_controller_activate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReferralControllerActivateError {
    Status400(models::BadRequestDto),
    Status401(models::UnauthorizedDto),
    Status403(models::ForbiddenDto),
    Status404(models::NotFoundDto),
    Status422(models::UnprocessableEntityDto),
    Status429(models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`referral_controller_claim_code`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReferralControllerClaimCodeError {
    Status400(models::BadRequestDto),
    Status401(models::UnauthorizedDto),
    Status403(models::ForbiddenDto),
    Status404(models::NotFoundDto),
    Status422(models::UnprocessableEntityDto),
    Status429(models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`referral_controller_get_code_usage`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReferralControllerGetCodeUsageError {
    Status400(models::BadRequestDto),
    Status401(models::UnauthorizedDto),
    Status403(models::ForbiddenDto),
    Status404(models::NotFoundDto),
    Status422(models::UnprocessableEntityDto),
    Status429(models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`referral_controller_get_summary`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReferralControllerGetSummaryError {
    Status400(models::BadRequestDto),
    Status401(models::UnauthorizedDto),
    Status403(models::ForbiddenDto),
    Status404(models::NotFoundDto),
    Status422(models::UnprocessableEntityDto),
    Status429(models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`referral_controller_list_referrals`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReferralControllerListReferralsError {
    Status400(models::BadRequestDto),
    Status401(models::UnauthorizedDto),
    Status403(models::ForbiddenDto),
    Status404(models::NotFoundDto),
    Status422(models::UnprocessableEntityDto),
    Status429(models::TooManyRequestsDto),
    Status500(),
    UnknownValue(serde_json::Value),
}

pub async fn referral_controller_activate(
    configuration: &configuration::Configuration,
    activate_referral_dto: models::ActivateReferralDto,
) -> Result<models::ReferralDto, Error<ReferralControllerActivateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_activate_referral_dto = activate_referral_dto;

    let uri_str = format!("{}/v1/referral/activate", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_activate_referral_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ReferralDto`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ReferralDto`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ReferralControllerActivateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn referral_controller_claim_code(
    configuration: &configuration::Configuration,
    claim_referral_code_dto: models::ClaimReferralCodeDto,
) -> Result<models::ReferralDto, Error<ReferralControllerClaimCodeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_claim_referral_code_dto = claim_referral_code_dto;

    let uri_str = format!("{}/v1/referral/claim", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_claim_referral_code_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ReferralDto`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ReferralDto`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ReferralControllerClaimCodeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn referral_controller_get_code_usage(
    configuration: &configuration::Configuration,
    code: &str,
) -> Result<models::ReferralCodeUsageDto, Error<ReferralControllerGetCodeUsageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_code = code;

    let uri_str = format!(
        "{}/v1/referral/code/{code}",
        configuration.base_path,
        code = crate::apis::urlencode(p_code)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ReferralCodeUsageDto`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ReferralCodeUsageDto`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ReferralControllerGetCodeUsageError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn referral_controller_get_summary(
    configuration: &configuration::Configuration,
    x_ethereal_auth: &str,
    x_ethereal_sender: &str,
    x_ethereal_signature: &str,
    x_ethereal_intent: &str,
    x_ethereal_signed_at: &str,
    subaccount: Option<&str>,
) -> Result<models::ReferralDto, Error<ReferralControllerGetSummaryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_x_ethereal_auth = x_ethereal_auth;
    let p_x_ethereal_sender = x_ethereal_sender;
    let p_x_ethereal_signature = x_ethereal_signature;
    let p_x_ethereal_intent = x_ethereal_intent;
    let p_x_ethereal_signed_at = x_ethereal_signed_at;
    let p_subaccount = subaccount;

    let uri_str = format!("{}/v1/referral/summary", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_subaccount {
        req_builder = req_builder.query(&[("subaccount", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Ethereal-Auth", p_x_ethereal_auth.to_string());
    req_builder = req_builder.header("X-Ethereal-Sender", p_x_ethereal_sender.to_string());
    req_builder = req_builder.header("X-Ethereal-Signature", p_x_ethereal_signature.to_string());
    req_builder = req_builder.header("X-Ethereal-Intent", p_x_ethereal_intent.to_string());
    req_builder = req_builder.header("X-Ethereal-SignedAt", p_x_ethereal_signed_at.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ReferralDto`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ReferralDto`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ReferralControllerGetSummaryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn referral_controller_list_referrals(
    configuration: &configuration::Configuration,
    x_ethereal_auth: &str,
    x_ethereal_sender: &str,
    x_ethereal_signature: &str,
    x_ethereal_intent: &str,
    x_ethereal_signed_at: &str,
    order: Option<&str>,
    limit: Option<f64>,
    cursor: Option<&str>,
    subaccount: Option<&str>,
    order_by: Option<&str>,
) -> Result<models::PageOfReferralDtos, Error<ReferralControllerListReferralsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_x_ethereal_auth = x_ethereal_auth;
    let p_x_ethereal_sender = x_ethereal_sender;
    let p_x_ethereal_signature = x_ethereal_signature;
    let p_x_ethereal_intent = x_ethereal_intent;
    let p_x_ethereal_signed_at = x_ethereal_signed_at;
    let p_order = order;
    let p_limit = limit;
    let p_cursor = cursor;
    let p_subaccount = subaccount;
    let p_order_by = order_by;

    let uri_str = format!("{}/v1/referral", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_subaccount {
        req_builder = req_builder.query(&[("subaccount", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_order_by {
        req_builder = req_builder.query(&[("orderBy", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Ethereal-Auth", p_x_ethereal_auth.to_string());
    req_builder = req_builder.header("X-Ethereal-Sender", p_x_ethereal_sender.to_string());
    req_builder = req_builder.header("X-Ethereal-Signature", p_x_ethereal_signature.to_string());
    req_builder = req_builder.header("X-Ethereal-Intent", p_x_ethereal_intent.to_string());
    req_builder = req_builder.header("X-Ethereal-SignedAt", p_x_ethereal_signed_at.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::PageOfReferralDtos`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::PageOfReferralDtos`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ReferralControllerListReferralsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
