/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateReferralDtoData {
    /// Account address that produced the authorizing signature
    #[serde(rename = "sender")]
    pub sender: String,
    /// Intent of the message (action to be taken)
    #[serde(rename = "intent")]
    pub intent: models::Eip712AuthIntent,
    /// Message signedAt current timestamp (seconds since Unix Epoch)
    #[serde(rename = "signedAt")]
    pub signed_at: i64,
    /// Bytes32 encoded subaccount name (0x prefix, zero padded)
    #[serde(rename = "subaccount")]
    pub subaccount: String,
}

impl ActivateReferralDtoData {
    pub fn new(
        sender: String,
        intent: models::Eip712AuthIntent,
        signed_at: i64,
        subaccount: String,
    ) -> ActivateReferralDtoData {
        ActivateReferralDtoData {
            sender,
            intent,
            signed_at,
            subaccount,
        }
    }
}
