/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BadRequestDtoMessage : Validation error message(s). Can be a single string or an array of strings.
/// Validation error message(s). Can be a single string or an array of strings.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BadRequestDtoMessage {
    String(String),
    Array(Vec<String>),
}

impl Default for BadRequestDtoMessage {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

