/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestDto {
    #[serde(rename = "statusCode")]
    pub status_code: StatusCode,
    #[serde(rename = "message")]
    pub message: models::BadRequestDtoMessage,
    #[serde(rename = "error")]
    pub error: Error,
}

impl BadRequestDto {
    pub fn new(
        status_code: StatusCode,
        message: models::BadRequestDtoMessage,
        error: Error,
    ) -> BadRequestDto {
        BadRequestDto {
            status_code,
            message,
            error,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusCode {
    #[serde(rename = "400")]
    Variant400,
}

impl Default for StatusCode {
    fn default() -> StatusCode {
        Self::Variant400
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "Bad Request")]
    BadRequest,
}

impl Default for Error {
    fn default() -> Error {
        Self::BadRequest
    }
}
