/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.  For more details, see [docs.ethereal.trade](https://docs.ethereal.trade).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestDto {
    #[serde(rename = "error")]
    pub error: models::ErrorEnum,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "statusCode")]
    pub status_code: StatusCode,
}

impl BadRequestDto {
    pub fn new(
        error: models::ErrorEnum,
        message: String,
        status_code: StatusCode,
    ) -> BadRequestDto {
        BadRequestDto {
            error,
            message,
            status_code,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusCode {
    #[serde(rename = "400")]
    Variant400,
}

impl Default for StatusCode {
    fn default() -> StatusCode {
        Self::Variant400
    }
}
