/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CategoryEnum : Extracted enum for CategoryEnum
/// Extracted enum for CategoryEnum
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CategoryEnum {
    #[serde(rename = "TRADE_SESSION")]
    TradeSession,
    #[serde(rename = "API")]
    Api,
}

impl std::fmt::Display for CategoryEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TradeSession => write!(f, "TRADE_SESSION"),
            Self::Api => write!(f, "API"),
        }
    }
}

impl Default for CategoryEnum {
    fn default() -> CategoryEnum {
        Self::TradeSession
    }
}
