/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.  For more details, see [docs.ethereal.trade](https://docs.ethereal.trade).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainTypeDto {
    /// The EIP-155 chain id
    #[serde(rename = "chainId")]
    pub chain_id: i64,
    /// Name of signing domain
    #[serde(rename = "name")]
    pub name: String,
    /// Address of the contract that will verify the signature
    #[serde(rename = "verifyingContract")]
    pub verifying_contract: String,
    /// Current major version of the signing domain
    #[serde(rename = "version")]
    pub version: String,
}

impl DomainTypeDto {
    pub fn new(
        chain_id: i64,
        name: String,
        verifying_contract: String,
        version: String,
    ) -> DomainTypeDto {
        DomainTypeDto {
            chain_id,
            name,
            verifying_contract,
            version,
        }
    }
}
