/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.  For more details, see [docs.ethereal.trade](https://docs.ethereal.trade).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DryRunOrderFailedUnprocessableEntityDto {
    /// Details of the failed dry run
    #[serde(rename = "data")]
    pub data: models::DryRunOrderFailedDto,
    #[serde(rename = "error")]
    pub error: models::DryRunOrderFailedUnprocessableEntityDtoErrorEnum,
    /// Code indicating the reason for failure
    #[serde(rename = "message")]
    pub message: models::SubmitOrderFailedResultCode,
    #[serde(rename = "statusCode")]
    pub status_code: StatusCode,
}

impl DryRunOrderFailedUnprocessableEntityDto {
    pub fn new(
        data: models::DryRunOrderFailedDto,
        error: models::DryRunOrderFailedUnprocessableEntityDtoErrorEnum,
        message: models::SubmitOrderFailedResultCode,
        status_code: StatusCode,
    ) -> DryRunOrderFailedUnprocessableEntityDto {
        DryRunOrderFailedUnprocessableEntityDto {
            data,
            error,
            message,
            status_code,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusCode {
    #[serde(rename = "422")]
    Variant422,
}

impl Default for StatusCode {
    fn default() -> StatusCode {
        Self::Variant422
    }
}
