/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
/// EngineTypeEnum : Extracted enum for EngineTypeEnum
/// Extracted enum for EngineTypeEnum
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum EngineTypeEnum {
    PERP = 0,
    SPOT = 1,
}

impl std::fmt::Display for EngineTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::PERP => "0",
                Self::SPOT => "1",
            }
        )
    }
}
impl Default for EngineTypeEnum {
    fn default() -> EngineTypeEnum {
        Self::PERP
    }
}
