/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtendLinkedSignerDto {
    /// The signature from signTypedData(...) signed by the signer
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "data")]
    pub data: models::ExtendLinkedSignerDtoData,
}

impl ExtendLinkedSignerDto {
    pub fn new(
        signature: String,
        data: models::ExtendLinkedSignerDtoData,
    ) -> ExtendLinkedSignerDto {
        ExtendLinkedSignerDto { signature, data }
    }
}
