/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForbiddenDtoErrorEnum : Extracted enum for ForbiddenDtoErrorEnum
/// Extracted enum for ForbiddenDtoErrorEnum
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ForbiddenDtoErrorEnum {
    #[serde(rename = "Forbidden")]
    Forbidden,
}

impl std::fmt::Display for ForbiddenDtoErrorEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Forbidden => write!(f, "Forbidden"),
        }
    }
}

impl Default for ForbiddenDtoErrorEnum {
    fn default() -> ForbiddenDtoErrorEnum {
        Self::Forbidden
    }
}
