/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
/// GroupContingencyTypeEnum : Extracted enum for GroupContingencyTypeEnum
/// Extracted enum for GroupContingencyTypeEnum
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum GroupContingencyTypeEnum {
    OTO = 0,
    OCO = 1,
}

impl std::fmt::Display for GroupContingencyTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::OTO => "0",
                Self::OCO => "1",
            }
        )
    }
}
impl Default for GroupContingencyTypeEnum {
    fn default() -> GroupContingencyTypeEnum {
        Self::OTO
    }
}
