/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HttpFixedRateLimitEndpointDtoOrderType : Extracted enum for HttpFixedRateLimitEndpointDtoOrderType
/// Extracted enum for HttpFixedRateLimitEndpointDtoOrderType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpFixedRateLimitEndpointDtoOrderType {
    #[serde(rename = "FIXED")]
    Fixed,
}

impl std::fmt::Display for HttpFixedRateLimitEndpointDtoOrderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Fixed => write!(f, "FIXED"),
        }
    }
}

impl Default for HttpFixedRateLimitEndpointDtoOrderType {
    fn default() -> HttpFixedRateLimitEndpointDtoOrderType {
        Self::Fixed
    }
}
