/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpPaginatedRateLimitEndpointDto {
    #[serde(rename = "method")]
    pub method: models::MethodEnum,
    /// API endpoint path
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "protocol")]
    pub protocol: models::ProtocolEnum,
    #[serde(rename = "type")]
    pub r#type: models::HttpPaginatedRateLimitEndpointDtoOrderType,
    /// Base points consumed per request
    #[serde(rename = "basePoints")]
    pub base_points: f64,
    /// Points consumed per row in paginated response
    #[serde(rename = "pointsPerRow")]
    pub points_per_row: f64,
}

impl HttpPaginatedRateLimitEndpointDto {
    pub fn new(
        method: models::MethodEnum,
        path: String,
        protocol: models::ProtocolEnum,
        r#type: models::HttpPaginatedRateLimitEndpointDtoOrderType,
        base_points: f64,
        points_per_row: f64,
    ) -> HttpPaginatedRateLimitEndpointDto {
        HttpPaginatedRateLimitEndpointDto {
            method,
            path,
            protocol,
            r#type,
            base_points,
            points_per_row,
        }
    }
}
