/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpFixedRateLimitEndpointDto {
    #[serde(rename = "method")]
    pub method: models::MethodEnum,
    /// API endpoint path
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "protocol")]
    pub protocol: models::ProtocolEnum,
    #[serde(rename = "type")]
    pub r#type: models::HttpFixedRateLimitEndpointDtoOrderType,
    /// Fixed points consumed per request
    #[serde(rename = "fixedPoints")]
    pub fixed_points: f64,
}

impl HttpFixedRateLimitEndpointDto {
    pub fn new(
        method: models::MethodEnum,
        path: String,
        protocol: models::ProtocolEnum,
        r#type: models::HttpFixedRateLimitEndpointDtoOrderType,
        fixed_points: f64,
    ) -> HttpFixedRateLimitEndpointDto {
        HttpFixedRateLimitEndpointDto {
            method,
            path,
            protocol,
            r#type,
            fixed_points,
        }
    }
}
