/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HttpPaginatedRateLimitEndpointDtoOrderType : Extracted enum for HttpPaginatedRateLimitEndpointDtoOrderType
/// Extracted enum for HttpPaginatedRateLimitEndpointDtoOrderType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpPaginatedRateLimitEndpointDtoOrderType {
    #[serde(rename = "PAGINATED")]
    Paginated,
}

impl std::fmt::Display for HttpPaginatedRateLimitEndpointDtoOrderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Paginated => write!(f, "PAGINATED"),
        }
    }
}

impl Default for HttpPaginatedRateLimitEndpointDtoOrderType {
    fn default() -> HttpPaginatedRateLimitEndpointDtoOrderType {
        Self::Paginated
    }
}
