/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
/// IntentEnum : Extracted enum for IntentEnum
/// Extracted enum for IntentEnum
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum IntentEnum {
    REFERRAL_ACTIVATION = 0,
    REFERRAL_CLAIM = 1,
    REFERRAL_READ = 2,
}

impl std::fmt::Display for IntentEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::REFERRAL_ACTIVATION => "0",
                Self::REFERRAL_CLAIM => "1",
                Self::REFERRAL_READ => "2",
            }
        )
    }
}
impl Default for IntentEnum {
    fn default() -> IntentEnum {
        Self::REFERRAL_ACTIVATION
    }
}
