/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOfPointsSeasonSummariesDtos {
    /// Array of points season summary objects
    #[serde(rename = "data")]
    pub data: Vec<models::PointsSeasonSummaryDto>,
}

impl ListOfPointsSeasonSummariesDtos {
    pub fn new(data: Vec<models::PointsSeasonSummaryDto>) -> ListOfPointsSeasonSummariesDtos {
        ListOfPointsSeasonSummariesDtos { data }
    }
}
