/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOfPointsPeriodDtos {
    /// Array of points period objects
    #[serde(rename = "data")]
    pub data: Vec<models::PointsPeriodDto>,
}

impl ListOfPointsPeriodDtos {
    pub fn new(data: Vec<models::PointsPeriodDto>) -> ListOfPointsPeriodDtos {
        ListOfPointsPeriodDtos { data }
    }
}
