/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOfMarketPriceDtos {
    /// Array of market price objects
    #[serde(rename = "data")]
    pub data: Vec<models::MarketPriceDto>,
}

impl ListOfMarketPriceDtos {
    pub fn new(data: Vec<models::MarketPriceDto>) -> ListOfMarketPriceDtos {
        ListOfMarketPriceDtos {
            data,
        }
    }
}

