/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
/// LzDestinationEidEnum : Extracted enum for LzDestinationEidEnum
/// Extracted enum for LzDestinationEidEnum
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum LzDestinationEidEnum {
    NONE = 0,
    ETHEREAL_TESTNET = 40422,
    ARBITRUM_SEPOLIA = 40231,
    ETHEREUM_SEPOLIA = 40161,
    ETHEREAL_MAINNET = 30391,
    ARBITRUM_MAINNET = 30110,
    ETHEREUM_MAINNET = 30101,
}

impl std::fmt::Display for LzDestinationEidEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::NONE => "0",
                Self::ETHEREAL_TESTNET => "40422",
                Self::ARBITRUM_SEPOLIA => "40231",
                Self::ETHEREUM_SEPOLIA => "40161",
                Self::ETHEREAL_MAINNET => "30391",
                Self::ARBITRUM_MAINNET => "30110",
                Self::ETHEREUM_MAINNET => "30101",
            }
        )
    }
}
impl Default for LzDestinationEidEnum {
    fn default() -> LzDestinationEidEnum {
        Self::NONE
    }
}
