/*
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderUpdateMessageDataDInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "cloid", skip_serializing_if = "Option::is_none")]
    pub cloid: Option<String>,
    #[serde(rename = "otyp")]
    pub otyp: Otyp,
    #[serde(rename = "qty")]
    pub qty: String,
    #[serde(rename = "aqty")]
    pub aqty: String,
    #[serde(rename = "fill")]
    pub fill: String,
    #[serde(rename = "px", skip_serializing_if = "Option::is_none")]
    pub px: Option<String>,
    #[serde(rename = "sd")]
    pub sd: Sd,
    #[serde(rename = "s")]
    pub s: String,
    #[serde(rename = "sid")]
    pub sid: uuid::Uuid,
    #[serde(rename = "sn")]
    pub sn: String,
    #[serde(rename = "st")]
    pub st: String,
    #[serde(rename = "t")]
    pub t: i64,
    #[serde(rename = "ro")]
    pub ro: bool,
    #[serde(rename = "cl")]
    pub cl: bool,
    #[serde(rename = "tif", skip_serializing_if = "Option::is_none")]
    pub tif: Option<String>,
    #[serde(rename = "et")]
    pub et: i64,
    #[serde(rename = "po", skip_serializing_if = "Option::is_none")]
    pub po: Option<bool>,
    #[serde(rename = "spx", skip_serializing_if = "Option::is_none")]
    pub spx: Option<String>,
    #[serde(rename = "styp", skip_serializing_if = "Option::is_none")]
    pub styp: Option<i32>,
    #[serde(rename = "spxtyp", skip_serializing_if = "Option::is_none")]
    pub spxtyp: Option<i32>,
    #[serde(rename = "tr")]
    pub tr: String,
    #[serde(rename = "gtyp", skip_serializing_if = "Option::is_none")]
    pub gtyp: Option<i32>,
    #[serde(rename = "gid", skip_serializing_if = "Option::is_none")]
    pub gid: Option<uuid::Uuid>,
}

impl OrderUpdateMessageDataDInner {
    pub fn new(
        id: uuid::Uuid,
        otyp: Otyp,
        qty: String,
        aqty: String,
        fill: String,
        sd: Sd,
        s: String,
        sid: uuid::Uuid,
        sn: String,
        st: String,
        t: i64,
        ro: bool,
        cl: bool,
        et: i64,
        tr: String,
    ) -> OrderUpdateMessageDataDInner {
        OrderUpdateMessageDataDInner {
            id,
            cloid: None,
            otyp,
            qty,
            aqty,
            fill,
            px: None,
            sd,
            s,
            sid,
            sn,
            st,
            t,
            ro,
            cl,
            tif: None,
            et,
            po: None,
            spx: None,
            styp: None,
            spxtyp: None,
            tr,
            gtyp: None,
            gid: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Otyp {
    #[serde(rename = "LIMIT")]
    Limit,
    #[serde(rename = "MARKET")]
    Market,
}

impl Default for Otyp {
    fn default() -> Otyp {
        Self::Limit
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Sd {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

impl Default for Sd {
    fn default() -> Sd {
        Self::Variant0
    }
}
