/*
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderFillMessage : Server-to-client OrderFill event message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderFillMessage {
    #[serde(rename = "e")]
    pub e: E,
    #[serde(rename = "t")]
    pub t: i64,
    #[serde(rename = "data")]
    pub data: models::OrderFillMessageData,
}

impl OrderFillMessage {
    /// Server-to-client OrderFill event message.
    pub fn new(e: E, t: i64, data: models::OrderFillMessageData) -> OrderFillMessage {
        OrderFillMessage { e, t, data }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum E {
    #[serde(rename = "OrderFill")]
    OrderFill,
}

impl Default for E {
    fn default() -> E {
        Self::OrderFill
    }
}
