/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.  For more details, see [docs.ethereal.trade](https://docs.ethereal.trade).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderDto {
    /// Remaining quantity (if modified or reduced) in native units expressed as a decimal (precision: 9)
    #[serde(rename = "availableQuantity")]
    pub available_quantity: rust_decimal::Decimal,
    /// A subaccount scoped unique client-generated order id (either a UUID or alphanumeric string up to 32 characters)
    #[serde(rename = "clientOrderId", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// Order closes the entire current position
    #[serde(rename = "close")]
    pub close: bool,
    /// Order creation timestamp (ms since Unix Epoch)
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    /// Order expiry timestamp (seconds since Unix Epoch)
    #[serde(rename = "expiresAt")]
    pub expires_at: i64,
    /// Filled amount in native units expressed as a decimal (precision: 9)
    #[serde(rename = "filled")]
    pub filled: rust_decimal::Decimal,
    /// Type of OTOCO relationship (OTO or OCO)
    #[serde(
        rename = "groupContingencyType",
        skip_serializing_if = "Option::is_none"
    )]
    pub group_contingency_type: Option<models::GroupContingencyType>,
    /// Id of the group this order belongs to
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<uuid::Uuid>,
    /// Id representing the order
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Only add order if it does not immediately fill (limit only)
    #[serde(rename = "postOnly", skip_serializing_if = "Option::is_none")]
    pub post_only: Option<bool>,
    /// Limit price in native units expressed as a decimal, zero if market order (precision: 9)
    #[serde(rename = "price")]
    pub price: rust_decimal::Decimal,
    /// Id of product this order was placed against
    #[serde(rename = "productId")]
    pub product_id: uuid::Uuid,
    /// Original quantity (as per order submission) in native units expressed as a decimal (precision: 9)
    #[serde(rename = "quantity")]
    pub quantity: rust_decimal::Decimal,
    /// Indicates if the order is reduce only
    #[serde(rename = "reduceOnly")]
    pub reduce_only: bool,
    #[serde(rename = "rejectedReason", skip_serializing_if = "Option::is_none")]
    pub rejected_reason: Option<models::RejectedReasonEnum>,
    /// Account or linked signer address that placed this order
    #[serde(rename = "sender")]
    pub sender: String,
    /// Side as either BUY (0) or SELL (1)
    #[serde(rename = "side")]
    pub side: models::OrderSide,
    #[serde(rename = "status")]
    pub status: models::OrderStatus,
    /// Stop price expressed as a decimal (zero if not a stop order, precision: 9)
    #[serde(rename = "stopPrice")]
    pub stop_price: rust_decimal::Decimal,
    /// Type of stop price (stop orders only)
    #[serde(rename = "stopPriceType", skip_serializing_if = "Option::is_none")]
    pub stop_price_type: Option<models::StopPriceType>,
    /// Stop type, either GAIN (0) for take-profit or LOSS (1) for stop-loss
    #[serde(rename = "stopType", skip_serializing_if = "Option::is_none")]
    pub stop_type: Option<models::StopType>,
    /// Id of the subaccount associated to order
    #[serde(rename = "subaccountId")]
    pub subaccount_id: uuid::Uuid,
    #[serde(rename = "timeInForce", skip_serializing_if = "Option::is_none")]
    pub time_in_force: Option<models::OrderTimeInForce>,
    #[serde(rename = "triggered")]
    pub triggered: models::TriggeredEnum,
    #[serde(rename = "type")]
    pub r#type: models::OrderDtoOrderType,
    /// Order last updated timestamp (ms since Unix Epoch)
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
}

impl OrderDto {
    pub fn new(
        available_quantity: rust_decimal::Decimal,
        close: bool,
        created_at: i64,
        expires_at: i64,
        filled: rust_decimal::Decimal,
        id: uuid::Uuid,
        price: rust_decimal::Decimal,
        product_id: uuid::Uuid,
        quantity: rust_decimal::Decimal,
        reduce_only: bool,
        sender: String,
        side: models::OrderSide,
        status: models::OrderStatus,
        stop_price: rust_decimal::Decimal,
        subaccount_id: uuid::Uuid,
        triggered: models::TriggeredEnum,
        r#type: models::OrderDtoOrderType,
        updated_at: i64,
    ) -> OrderDto {
        OrderDto {
            available_quantity,
            client_order_id: None,
            close,
            created_at,
            expires_at,
            filled,
            group_contingency_type: None,
            group_id: None,
            id,
            post_only: None,
            price,
            product_id,
            quantity,
            reduce_only,
            rejected_reason: None,
            sender,
            side,
            status,
            stop_price,
            stop_price_type: None,
            stop_type: None,
            subaccount_id,
            time_in_force: None,
            triggered,
            r#type,
            updated_at,
        }
    }
}
