/*
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderFillMessageDataDInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "oid")]
    pub oid: uuid::Uuid,
    #[serde(rename = "cloid")]
    pub cloid: String,
    #[serde(rename = "px")]
    pub px: String,
    #[serde(rename = "sz")]
    pub sz: String,
    #[serde(rename = "typ")]
    pub typ: models::OrderType,
    #[serde(rename = "sd")]
    pub sd: models::OrderSide,
    #[serde(rename = "s")]
    pub s: String,
    #[serde(rename = "sid")]
    pub sid: uuid::Uuid,
    #[serde(rename = "ro")]
    pub ro: bool,
    #[serde(rename = "fee")]
    pub fee: String,
    #[serde(rename = "m")]
    pub m: bool,
    #[serde(rename = "t")]
    pub t: i64,
}

impl OrderFillMessageDataDInner {
    pub fn new(
        id: uuid::Uuid,
        oid: uuid::Uuid,
        cloid: String,
        px: String,
        sz: String,
        typ: models::OrderType,
        sd: models::OrderSide,
        s: String,
        sid: uuid::Uuid,
        ro: bool,
        fee: String,
        m: bool,
        t: i64,
    ) -> OrderFillMessageDataDInner {
        OrderFillMessageDataDInner {
            id,
            oid,
            cloid,
            px,
            sz,
            typ,
            sd,
            s,
            sid,
            ro,
            fee,
            m,
            t,
        }
    }
}
