/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.  For more details, see [docs.ethereal.trade](https://docs.ethereal.trade).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageOfPositionLiquidationsDto {
    /// Array of position liquidation objects
    #[serde(rename = "data")]
    pub data: Vec<models::PositionLiquidationDto>,
    /// Whether there are more objects to paginate through
    #[serde(rename = "hasNext")]
    pub has_next: bool,
    /// Pointer to the next page in pagination dataset
    #[serde(rename = "nextCursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl PageOfPositionLiquidationsDto {
    pub fn new(
        data: Vec<models::PositionLiquidationDto>,
        has_next: bool,
    ) -> PageOfPositionLiquidationsDto {
        PageOfPositionLiquidationsDto {
            data,
            has_next,
            next_cursor: None,
        }
    }
}
