/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageOfExchangeOpenInterestHistoryDtos {
    /// Whether there are more objects to paginate through
    #[serde(rename = "hasNext")]
    pub has_next: bool,
    /// Pointer to the next page in pagination dataset
    #[serde(rename = "nextCursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    /// Array of exchange open interest history records
    #[serde(rename = "data")]
    pub data: Vec<models::ExchangeOpenInterestHistoryDto>,
}

impl PageOfExchangeOpenInterestHistoryDtos {
    pub fn new(
        has_next: bool,
        data: Vec<models::ExchangeOpenInterestHistoryDto>,
    ) -> PageOfExchangeOpenInterestHistoryDtos {
        PageOfExchangeOpenInterestHistoryDtos {
            has_next,
            next_cursor: None,
            data,
        }
    }
}
