/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
/// PositionSideEnum : Extracted enum for PositionSideEnum
/// Extracted enum for PositionSideEnum
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum PositionSideEnum {
    BUY = 0,
    SELL = 1,
}

impl std::fmt::Display for PositionSideEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::BUY => "0",
                Self::SELL => "1",
            }
        )
    }
}
impl Default for PositionSideEnum {
    fn default() -> PositionSideEnum {
        Self::BUY
    }
}
