/*
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PositionUpdateMessageData {
    /// Timestamp in milliseconds of the position update.
    #[serde(rename = "t")]
    pub t: i64,
    #[serde(rename = "d")]
    pub d: Vec<models::PositionUpdateMessageDataDInner>,
}

impl PositionUpdateMessageData {
    pub fn new(
        t: i64,
        d: Vec<models::PositionUpdateMessageDataDInner>,
    ) -> PositionUpdateMessageData {
        PositionUpdateMessageData { t, d }
    }
}
