/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcConfigDto {
    /// Domain type
    #[serde(rename = "domain")]
    pub domain: models::DomainTypeDto,
    /// Signature types
    #[serde(rename = "signatureTypes")]
    pub signature_types: models::SignatureTypesDto,
}

impl RpcConfigDto {
    pub fn new(
        domain: models::DomainTypeDto,
        signature_types: models::SignatureTypesDto,
    ) -> RpcConfigDto {
        RpcConfigDto {
            domain,
            signature_types,
        }
    }
}
