/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
/// StopTypeEnum : Extracted enum for StopTypeEnum
/// Extracted enum for StopTypeEnum
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum StopTypeEnum {
    GAIN = 0,
    LOSS = 1,
}

impl std::fmt::Display for StopTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::GAIN => "0",
                Self::LOSS => "1",
            }
        )
    }
}
impl Default for StopTypeEnum {
    fn default() -> StopTypeEnum {
        Self::GAIN
    }
}
