/*
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountLiquidationMessageDataDInner {
    /// Symbol.
    #[serde(rename = "s")]
    pub s: String,
    /// Price.
    #[serde(rename = "px")]
    pub px: rust_decimal::Decimal,
    /// Size.
    #[serde(rename = "sz")]
    pub sz: rust_decimal::Decimal,
}

impl SubaccountLiquidationMessageDataDInner {
    pub fn new(
        s: String,
        px: rust_decimal::Decimal,
        sz: rust_decimal::Decimal,
    ) -> SubaccountLiquidationMessageDataDInner {
        SubaccountLiquidationMessageDataDInner { s, px, sz }
    }
}
