/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubaccountLiquidation {
    /// Id representing the registered subaccount
    #[serde(rename = "subaccountId")]
    pub subaccount_id: uuid::Uuid,
    /// Timestamp of when the subaccount was liquidated (ms since Unix Epoch)
    #[serde(rename = "liquidatedAt")]
    pub liquidated_at: f64,
}

impl SubaccountLiquidation {
    pub fn new(subaccount_id: uuid::Uuid, liquidated_at: f64) -> SubaccountLiquidation {
        SubaccountLiquidation {
            subaccount_id,
            liquidated_at,
        }
    }
}
