/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitOrderDto {
    #[serde(rename = "data")]
    pub data: Box<models::SubmitOrderDtoData>,
    /// The signature from signTypedData(...) signed by the sender
    #[serde(rename = "signature")]
    pub signature: String,
}

impl SubmitOrderDto {
    pub fn new(data: models::SubmitOrderDtoData, signature: String) -> SubmitOrderDto {
        SubmitOrderDto {
            data: Box::new(data),
            signature,
        }
    }
}

