/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitOrderCreatedDto {
    /// Id representing the created order
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// A subaccount scoped unique client-generated order id (either a UUID or alphanumeric string up to 32 characters)
    #[serde(rename = "clientOrderId", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// Filled amount in native units expressed as a decimal (precision: 9). Always zero when block execution is enabled.
    #[serde(rename = "filled")]
    pub filled: rust_decimal::Decimal,
    /// Code indicating the result of the submission
    #[serde(rename = "result")]
    pub result: models::SubmitOrderCreatedResultCode,
}

impl SubmitOrderCreatedDto {
    pub fn new(
        id: uuid::Uuid,
        filled: rust_decimal::Decimal,
        result: models::SubmitOrderCreatedResultCode,
    ) -> SubmitOrderCreatedDto {
        SubmitOrderCreatedDto {
            id,
            client_order_id: None,
            filled,
            result,
        }
    }
}
