/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubmitOrderDtoData {
    SubmitOrderMarketDtoData(models::SubmitOrderMarketDtoData),
    SubmitOrderLimitDtoData(models::SubmitOrderLimitDtoData),
}

impl Default for SubmitOrderDtoData {
    fn default() -> Self {
        Self::SubmitOrderMarketDtoData(Default::default())
    }
}
