/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.  For more details, see [docs.ethereal.trade](https://docs.ethereal.trade).
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubmitOrderCreatedDto : Response returned when order is successfully submitted
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitOrderCreatedDto {
    /// Client-provided order id (if supplied in request)
    #[serde(rename = "clientOrderId", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// Quantity filled expressed as a decimal string (precision: 9)  **Deprecated:** This value is always zero when block execution is enabled.
    #[serde(rename = "filled")]
    pub filled: rust_decimal::Decimal,
    /// Id representing the order
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Result code indicating the outcome of the submission
    #[serde(rename = "result")]
    pub result: models::SubmitCreatedCode,
}

impl SubmitOrderCreatedDto {
    /// Response returned when order is successfully submitted
    pub fn new(
        filled: rust_decimal::Decimal,
        id: uuid::Uuid,
        result: models::SubmitCreatedCode,
    ) -> SubmitOrderCreatedDto {
        SubmitOrderCreatedDto {
            client_order_id: None,
            filled,
            id,
            result,
        }
    }
}
