/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitOrderDto {
    #[serde(rename = "data")]
    pub data: models::SubmitOrderDtoData,
    /// Hex-encoded EIP-712 signature authorizing this request
    #[serde(rename = "signature")]
    pub signature: String,
}

impl SubmitOrderDto {
    pub fn new(data: models::SubmitOrderDtoData, signature: String) -> SubmitOrderDto {
        SubmitOrderDto { data, signature }
    }
}
