/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitOrderFailedDto {
    #[serde(rename = "statusCode")]
    pub status_code: StatusCode,
    #[serde(rename = "message")]
    pub message: models::MessageEnum,
    #[serde(rename = "error")]
    pub error: models::SubmitOrderFailedDtoErrorEnum,
}

impl SubmitOrderFailedDto {
    pub fn new(
        status_code: StatusCode,
        message: models::MessageEnum,
        error: models::SubmitOrderFailedDtoErrorEnum,
    ) -> SubmitOrderFailedDto {
        SubmitOrderFailedDto {
            status_code,
            message,
            error,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusCode {
    #[serde(rename = "422")]
    Variant422,
}

impl Default for StatusCode {
    fn default() -> StatusCode {
        Self::Variant422
    }
}
