/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemTimeDto {
    /// Current system timestamp (ms since Unix Epoch)
    #[serde(rename = "time")]
    pub time: f64,
}

impl SystemTimeDto {
    pub fn new(time: f64) -> SystemTimeDto {
        SystemTimeDto {
            time,
        }
    }
}

