/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// TakerSide : Side of the trade
/// Side of the trade
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum TakerSide {
    BUY = 0,
    SELL = 1,

}

impl std::fmt::Display for TakerSide {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::BUY => "0",
            Self::SELL => "1",
        })
    }
}
impl Default for TakerSide {
    fn default() -> TakerSide {
        Self::BUY
    }
}

