/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TickerWsDto {
    #[serde(rename = "e")]
    pub e: models::EEnum,
    /// Server timestamp (ms since Unix Epoch)
    #[serde(rename = "t")]
    pub t: f64,
    #[serde(rename = "data")]
    pub data: models::TickerWsDataDto,
}

impl TickerWsDto {
    pub fn new(e: models::EEnum, t: f64, data: models::TickerWsDataDto) -> TickerWsDto {
        TickerWsDto { e, t, data }
    }
}
