/*
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TickerMessage : Server-to-client Ticker event message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TickerMessage {
    /// Event type.
    #[serde(rename = "e")]
    pub e: E,
    /// System timestamp in milliseconds when this message was emitted.
    #[serde(rename = "t")]
    pub t: i64,
    #[serde(rename = "data")]
    pub data: models::TickerMessageData,
}

impl TickerMessage {
    /// Server-to-client Ticker event message.
    pub fn new(e: E, t: i64, data: models::TickerMessageData) -> TickerMessage {
        TickerMessage { e, t, data }
    }
}
/// Event type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum E {
    #[serde(rename = "Ticker")]
    Ticker,
}

impl Default for E {
    fn default() -> E {
        Self::Ticker
    }
}
