/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
/// TierEnum : Extracted enum for TierEnum
/// Extracted enum for TierEnum
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum TierEnum {
    TIER_0 = 0,
    TIER_1 = 1,
    TIER_2 = 2,
    TIER_3 = 3,
    TIER_4 = 4,
    TIER_5 = 5,
}

impl std::fmt::Display for TierEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::TIER_0 => "0",
                Self::TIER_1 => "1",
                Self::TIER_2 => "2",
                Self::TIER_3 => "3",
                Self::TIER_4 => "4",
                Self::TIER_5 => "5",
            }
        )
    }
}
impl Default for TierEnum {
    fn default() -> TierEnum {
        Self::TIER_0
    }
}
