/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TooManyRequestsDtoErrorEnum : Extracted enum for TooManyRequestsDtoErrorEnum
/// Extracted enum for TooManyRequestsDtoErrorEnum
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TooManyRequestsDtoErrorEnum {
    #[serde(rename = "Too Many Requests")]
    TooManyRequests,
}

impl std::fmt::Display for TooManyRequestsDtoErrorEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::TooManyRequests => write!(f, "Too Many Requests"),
        }
    }
}

impl Default for TooManyRequestsDtoErrorEnum {
    fn default() -> TooManyRequestsDtoErrorEnum {
        Self::TooManyRequests
    }
}
