/*
 * Ethereal Archive API
 *
 * Ethereal HTTP API for archived data, providing historical balance, volume, and PnL data.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotalProductVolumeDtos {
    /// Array of product total volume records
    #[serde(rename = "data")]
    pub data: Vec<models::TotalProductVolumeDto>,
}

impl TotalProductVolumeDtos {
    pub fn new(data: Vec<models::TotalProductVolumeDto>) -> TotalProductVolumeDtos {
        TotalProductVolumeDtos { data }
    }
}
