/*
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradeFillMessageData {
    /// Market symbol.
    #[serde(rename = "s")]
    pub s: String,
    /// Timestamp in milliseconds for this trade update.
    #[serde(rename = "t")]
    pub t: i64,
    /// Array of trade fill objects.
    #[serde(rename = "d")]
    pub d: Vec<models::TradeFillMessageDataDInner>,
}

impl TradeFillMessageData {
    pub fn new(
        s: String,
        t: i64,
        d: Vec<models::TradeFillMessageDataDInner>,
    ) -> TradeFillMessageData {
        TradeFillMessageData { s, t, d }
    }
}
