/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferDtoOrderStatus : Extracted enum for TransferDtoOrderStatus
/// Extracted enum for TransferDtoOrderStatus
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferDtoOrderStatus {
    #[serde(rename = "SUBMITTED")]
    Submitted,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "REJECTED")]
    Rejected,
}

impl std::fmt::Display for TransferDtoOrderStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Submitted => write!(f, "SUBMITTED"),
            Self::Pending => write!(f, "PENDING"),
            Self::Completed => write!(f, "COMPLETED"),
            Self::Rejected => write!(f, "REJECTED"),
        }
    }
}

impl Default for TransferDtoOrderStatus {
    fn default() -> TransferDtoOrderStatus {
        Self::Submitted
    }
}
