/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnauthorizedDto {
    #[serde(rename = "statusCode")]
    pub status_code: StatusCode,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "error")]
    pub error: Error,
}

impl UnauthorizedDto {
    pub fn new(status_code: StatusCode, message: String, error: Error) -> UnauthorizedDto {
        UnauthorizedDto {
            status_code,
            message,
            error,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusCode {
    #[serde(rename = "401")]
    Variant401,
}

impl Default for StatusCode {
    fn default() -> StatusCode {
        Self::Variant401
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "Unauthorized")]
    Unauthorized,
}

impl Default for Error {
    fn default() -> Error {
        Self::Unauthorized
    }
}
