/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WhitelistDto {
    /// Whether the address is whitelisted
    #[serde(rename = "isWhitelisted")]
    pub is_whitelisted: bool,
}

impl WhitelistDto {
    pub fn new(is_whitelisted: bool) -> WhitelistDto {
        WhitelistDto {
            is_whitelisted,
        }
    }
}

