/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawFailedDto {
    #[serde(rename = "statusCode")]
    pub status_code: StatusCode,
    /// Error code indicating the reason for failure
    #[serde(rename = "message")]
    pub message: Message,
    #[serde(rename = "error")]
    pub error: Error,
}

impl WithdrawFailedDto {
    pub fn new(status_code: StatusCode, message: Message, error: Error) -> WithdrawFailedDto {
        WithdrawFailedDto {
            status_code,
            message,
            error,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusCode {
    #[serde(rename = "422")]
    Variant422,
}

impl Default for StatusCode {
    fn default() -> StatusCode {
        Self::Variant422
    }
}
/// Error code indicating the reason for failure
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "AccountSuspended")]
    AccountSuspended,
    #[serde(rename = "EngineSuspended")]
    EngineSuspended,
    #[serde(rename = "InsufficientBalance")]
    InsufficientBalance,
    #[serde(rename = "InsuranceFundCannotWithdraw")]
    InsuranceFundCannotWithdraw,
}

impl Default for Message {
    fn default() -> Message {
        Self::AccountSuspended
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "Unprocessable Entity")]
    UnprocessableEntity,
}

impl Default for Error {
    fn default() -> Error {
        Self::UnprocessableEntity
    }
}

