/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WithdrawFailedDtoErrorEnum : Extracted enum for WithdrawFailedDtoErrorEnum
/// Extracted enum for WithdrawFailedDtoErrorEnum
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WithdrawFailedDtoErrorEnum {
    #[serde(rename = "Unprocessable Entity")]
    UnprocessableEntity,
}

impl std::fmt::Display for WithdrawFailedDtoErrorEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UnprocessableEntity => write!(f, "Unprocessable Entity"),
        }
    }
}

impl Default for WithdrawFailedDtoErrorEnum {
    fn default() -> WithdrawFailedDtoErrorEnum {
        Self::UnprocessableEntity
    }
}
