/*
 * Ethereal Exchange API
 *
 * Ethereal HTTP API for real-time trading, order management, and market data access.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WsFixedRateLimitEndpointDtoProtocolEnum : Extracted enum for WsFixedRateLimitEndpointDtoProtocolEnum
/// Extracted enum for WsFixedRateLimitEndpointDtoProtocolEnum
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WsFixedRateLimitEndpointDtoProtocolEnum {
    #[serde(rename = "WS")]
    Ws,
}

impl std::fmt::Display for WsFixedRateLimitEndpointDtoProtocolEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ws => write!(f, "WS"),
        }
    }
}

impl Default for WsFixedRateLimitEndpointDtoProtocolEnum {
    fn default() -> WsFixedRateLimitEndpointDtoProtocolEnum {
        Self::Ws
    }
}
